openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://task-api-a95m.onrender.com
    description: Production server on render

tags:
  - name: Tasks
    description: tasks-related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yml
